apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: gitops-app
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: dwk-repo
  interval: 10m
  path: todo
  prune: true
  validation: client
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nats
  namespace: flux-system
resources:
  - helm-releases.yml
  - helm-repositories.yml
