apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRepository
metadata:
  name: flux-system-nats
  namespace: flux-system
spec:
  interval: 1m
  url: https://nats-io.github.io/k8s/helm/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 1m
  url: https://prometheus-community.github.io/helm-charts
