apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: project
spec:
  interval: 5m
  chart:
    spec:
      chart: nats
      version: "0.17.x"
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: project
      interval: 1m
  values:
    replicaCount: 2
