apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm-repositories.yml
      version: "0.7.x"
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
