apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: dwk-repo
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/dawidl022/mooc-fi-kubernetes
  ref:
    branch: master
